sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: R5qvV1c4FuxnhQwa3oLIqFBE5z8CB5X/WQeTbX7+XqCV3IbuV9c4YqbAp7x0/NEFTEH8gyPBXfw7whdTjZPL/M8kku6zeBcDzbfVCYnke98Qx1cCIfy6nASuGVdpD+LlfPniZk0NFe7RwUdLA0+2UFgdiGon/ov60Olio6wH1yzhTE7PqIOzVK+0QhfPer4sXC9bcRRMwSzMx6ffL9R3i+7RnpVgFGl1BFV+R4IaCSMn9j7dzlf8sRUp5jWY5itboM2QQjB632W8v/v6lxijFg+ASQOuSy1bf/jHZGn+5+WiqGxq97u796xnnhgPizW6wYdA7zxy9faisnW4FVCfd1VrWtJBuZ1t4dCR/Eo3ed0hx0WRSWDmqUHr0mRlK4lonBiuRvu/i2RcoHaWyC+mYpXYJN048QK1RlKwY/mSZZryT8B7DydYvQ5ux9K5+2uEuy1BztiYat7xLOEAKAuMaq9N6BMzgwRdMj8+VF09AjkcRbyHB9omaP5dkxnEzMtaoNMaMqS/RrSUPFxuwtUp9/ptPG64QJfy3796d1WbIyeW6IePpx/bdJXQb4oJVujthczDZsQr/CrmS6oo6z0x8cssnRYFU2aB15RZEvQ1B0FBTrNSldtqNUDlbSLihVRZ9gqeM6Qq8VJW8A90Bk/ByPrIzsnTY2z5b3XzU2Kl6Rc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Arachne-Volume-03_5510
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy